baseURL = "https://docs-qa.med-web.com/eh"
languageCode = "en-us"
title = "Enterprise Health"
theme = "wc-eh-docs"
publishDir = "public/eh"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "MIEDocs"
  author = "Enterprise Health"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  [params.brand]
    name = 'Enterprise Health'
    abbr = 'EH'
    code = 'eh' 
[outputs]
  home = [ "HTML", "RSS", "JSON"]
[markup.goldmark.renderer]
  unsafe= true
