# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, docsqa ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build WebChart HTML
      run: hugo --config 'config-wc.toml'

    - name: Build Enterprise Health HTML
      run: hugo --config 'config-eh.toml'

    - name: 'Deploy built documentation to www folder on docs-qa'
      run: rsync -ruva public /www/mie-docs/

    - name: Rocket.Chat Notification
      uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*CI*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#miedocs'
        url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
        # We should enable this once we figure out why this doesn't work.
        # commit: true
        # token: ${{ secrets.GHE_TOKEN }}
